[tool.poetry]
name = "d-fast_morphological_impact"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.9.13"
numpy = "^1.24.1"
netCDF4 = "^1.6.2"
Fiona = "^1.8.22"
pandas = "^1.5.2"
tbb = "2021.7.1"
mkl = "2021.4.0"
PyQt5 = "^5.15.7"
ordered-set = "^4.1.0"
pyproj = "^3.4.1"
cftime = "1.3.0"

[tool.poetry.dev-dependencies]
pytest = "^7.2.1"
black = "^22.12.0"
Nuitka = "^1.3.8"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
